version: '3.9'

services:
  mongodb:
      image: mongo:latest
      restart: always
      ports:
        - '27017:27017'

  ping:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ping_image:latest
    command: python ./code/ping_connection.py
    volumes:
        - 'telemetry_data:/data/file'

  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
  sparkwrite:
      build: 
        context: .
        dockerfile: Dockerfile
      image: spark_stream_write_image:latest
      command: python ./code/write_to_mongodb.py
  
  readmongodb:
      build: 
        context: .
        dockerfile: Dockerfile
      image: read_mongodb_data_image:latest
      command: python ./code/read_db_data.py
      
volumes:
    telemetry_data:


      

